# Generated by Django 5.1 on 2025-09-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='accuracy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.CharField(choices=[('IOD', 'MIT Institute of Design (IOD)'), ('ISBJ', 'International School of Broadcasting & Journalism (ISBJ)'), ('MANET', 'Maharashtra Academy of Naval Engineering and Training'), ('MITCOM', 'MIT College of Management'), ('SBSR', 'MIT School of Bioengineering Science & Research'), ('SFTh', 'MIT School of Film and Theatre'), ('SICS', 'MIT School of Indian Civil Services'), ('SOA', 'MIT School of Architecture'), ('SOC', 'MIT School of Computing'), ('SOER', 'MIT School of Education & Research'), ('SOES', 'MIT School of Engineering and Sciences'), ('SOFA', 'MIT School of Fine Art & Applied Art'), ('SoFT', 'MIT School of Food Technology'), ('SOH', 'MIT School of Humanities'), ('SOL', 'MIT School of Law'), ('SVS', 'School of Vedic Sciences'), ('VSKA', 'MIT Vishwashanti Sangeet Kala Academy')], default='IOD', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='purposes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='tools',
            field=models.CharField(choices=[('ChatGPT', 'ChatGPT'), ('Bard', 'Google Bard'), ('Bing', 'Microsoft Bing Chat'), ('Copilot', 'GitHub Copilot'), ('Claude', 'Claude'), ('Midjourney', 'Midjourney'), ('DALL-E', 'DALL·E'), ('Gemini', 'Gemini'), ('DeepSeek', 'DeepSeek'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
