# Generated by Django 5.1 on 2025-09-21 07:04

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact_accuracy_contact_department_contact_purposes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='purposes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Coding', 'Coding'), ('Research', 'Research'), ('Design', 'Design'), ('Career Prep', 'Career Prep'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=2),
        ),
    ]
